//////////////////////////////////////////////////////////////////////////
/*
Copyright (c) 2011-2015 Kaiming Yi
	
	Permission is hereby granted, free of charge, to any person obtaining a copy
	of this software and associated documentation files (the "Software"), to deal
	in the Software without restriction, including without limitation the rights
	to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
	copies of the Software, and to permit persons to whom the Software is
	furnished to do so, subject to the following conditions:
	
	The above copyright notice and this permission notice shall be included in
	all copies or substantial portions of the Software.
	
	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
	THE SOFTWARE.
	
*/
//////////////////////////////////////////////////////////////////////////



//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RibbonSample.rc
//
#define IDR_MANIFEST                    1
#define IDR_CNTR_INPLACE                6
#define IDP_OLE_INIT_FAILED             100
#define IDC_TODPROPERTY                 101
#define IDP_FAILED_TO_CREATE            102
#define IDC_MATEDTPROPERTY              103
#define IDD_DIALOGBAR                   103
#define IDD_WORKSPACETITLE              103
#define IDC_TODPROPERTY2                104
#define IDC_PANEOBJPROPERTY             104
#define IDR_HTML_PANECONSOLEVAR         105
#define IDC_PANEOBJPROPERTY2            105
#define IDC_PANECONSOLEVAR              105
#define IDS_SWISSKNIFEBAR_CREATION      106
#define IDS_SWISSKNIFEBAR_MODIFY        107
#define IDS_SWISSKNIFEBAR_DISPLAY       108
#define IDR_MAINFRAME                   128
#define IDR_SMALLICONS                  128
#define IDR_RIBBONTYPE                  129
#define IDR_LARGEICONS                  131
#define ID_STYLES_QUICKSTYLES           131
#define IDR_LAYOUTTABSMALL              143
#define IDR_LAYOUTTABLARGE              145
#define IDR_MENU_CONTEXT                147
#define ID_APP_THEME                    148
#define IDB_BITMAP_PICTURE              149
#define IDB_BITMAP_GRAPHIC              150
#define IDB_BITMAP_CHART                151
#define IDB_BITMAP_TABLE                152
#define ID_INSERT_SHAPES                154
#define IDR_MENU_OPTIONS                155
#define IDD_DIALOG1                     157
#define IDR_MENU_PRINT                  175
#define IDR_MENU_MINITOOLBAR            177
#define IDR_MENU_SEND                   178
#define IDD_PANE_STYLES                 182
#define IDD_PANE_CONSOLE                183
#define IDB_BITMAP1                     187
#define IDD_TODDLG                      195
#define IDD_MATERIALEDITOR              196
#define IDR_TOOLBAR1                    197
#define IDD_DIALOG2                     199
#define IDD_PANE_CONSOLEVAR             199
#define IDB_INSERTTAB                   200
#define IDB_WRITETAB                    201
#define IDB_BITMAPS_GROUPS              202
#define IDR_TOOLBAR_MATERIALEDITOR      203
#define IDR_TOOLBAR_MATERIALEDITO       205
#define IDB_ICONSUBEDITOR               207
#define IDD_DIALOG3                     208
#define IDD_STARTBANNER                 208
#define IDB_BITMAP_STARTBANNER          209
#define IDB_BITMAP2                     210
#define IDB_MATEDTLIST                  210
#define IDB_BITMAP3                     212
#define IDB_GRIDPROPERTY                212
#define IDB_SWISSKNIFE_BIG              214
#define IDB_SWISSKNIFE_SMALL            215
#define IDB_SWISSBAR_BIGA               217
#define IDB_PNG2                        218
#define IDB_SWISSBAR_SMALLA             218
#define IDB_BITMAP4                     219
#define IDB_SKB_ICONLIST                219
#define ID_INDICATOR_PAGENUMBER         220
#define IDB_PNG1                        220
#define ID_INDICATOR_WORDCOUNT          221
#define IDR_PANES                       221
#define IDR_PANES_CONSOLE               221
#define ID_INDICATOR_LANGUAGE           222
#define ID_INDICATOR_TRACKCHANGES       223
#define ID_INDICATOR_CAPSLOCK           224
#define ID_INDICATOR_OVERTYPE           225
#define ID_INDICATOR_MACRORECORDING     226
#define ID_INDICATOR_VIEWSHORTCUTS      227
#define ID_INDICATOR_ZOOM               228
#define ID_INDICATOR_ZOOMSLIDER         229
#define ID_INDICATOR_PROGRESS           230
#define IDB_GEAR                        300
#define ID_GALLERY_COLORS               773
#define ID_GALLERY_FONTS                774
#define ID_QUICKSTYLES_SAVESTYLE        777
#define ID_GALLERY_FONTTEXTCOLOR        778
#define ID_GALLERY_FONTBACKCOLOR        779
#define IDB_GROUPOPTIONTOOLTIP          1001
#define IDC_LIST_STYLES                 1005
#define IDC_CHECK_PREVIEW               1006
#define IDC_CHECK_LINKEDSTYLE           1007
#define IDC_BUTTON_NEWSTYLE             1008
#define IDC_BUTTON_STYLEINSPECTOR       1009
#define IDC_BUTTON_MANAGESTYLES         1010
#define IDC_BUTTON_CVAR                 1010
#define IDC_BUTTON_MANAGESTYLES2        1011
#define IDC_LIST_CONSLOE                1011
#define IDC_LIST_CONSOLE                1011
#define IDC_EDIT1                       1012
#define IDC_EDIT_CVSEARCH               1012
#define IDC_PROPPLACEHOLDER             1013
#define IDC_SLIDER1                     1014
#define IDC_TODSLIDER                   1014
#define IDC_TOD_PLAY                    1015
#define IDC_TOD_STOP                    1016
#define IDC_MATEDTLIST                  1016
#define IDC_TOD_PREVKEY                 1017
#define IDC_MATEDTGRID                  1017
#define IDC_TOD_NEXTKEY                 1018
#define IDC_MATEDTSET                   1018
#define IDC_TOD_PLANTKEY                1019
#define IDC_MATEDTGET                   1019
#define IDC_TOD_PREVKEY4                1020
#define IDC_TOD_DELETEKEY               1020
#define IDC_MATEDTGET2                  1020
#define IDC_MATEDTREFRESH               1020
#define IDC_PANEOBJ_PLACEHOLDER         1020
#define IDC_PANE_CONSOLEVAR_PLACEHOLDER 1021
#define IDC_STATIC_CVSEARCH             1023
#define IDC_RICHEDIT21                  1024
#define IDC_RICHEDIT_CONSOLELIST        1024
#define IDC_WORKSPACETITLE              1025
#define IDC_WORKSPACE_SHOWHELPER        1026
#define IDC_TRAN                        1027
#define IDC_STARTTEXT                   1028
#define IDC_TREE1                       1029
#define IDC_PSCP_COLOR_AREA1            1030
#define IDC_PSCP_COLOR_AREA2            1031
#define IDB_PROPERTYGRID_ICON           1032
#define IDC_PSCP_RED                    1032
#define IDD_PSCP                        1033
#define IDC_PSCP_GREEN                  1033
#define IDC_PSCP_BLUE                   1034
#define IDC_PSCP_COLORREF               1035
#define IDC_PSCP_RCHECKER               1036
#define IDC_PSCP_GCHECKER               1037
#define IDC_PSCP_BCHECKER               1038
#define IDC_PSCP_HUE                    1039
#define IDC_PSCP_SAT                    1040
#define IDC_PSCP_LUM                    1041
#define IDC_PSCP_HCHECKER               1042
#define IDC_PSCP_SCHECKER               1043
#define IDC_PSCP_LCHECKER               1044
#define ID_GROUP_BUTTONPOPUP            2000
#define ID_INSERT_HYPERLINK             2710
#define ID_INSERT_CROSS_REFERENCE       2712
#define ID_TEXT_SIGNATURE               2713
#define ID_TEXT_DATETIME                2714
#define ID_TEXT_INSERTOBJECT            2715
#define ID_GALLERY_FONTSIZE             2716
#define ID_SWITCH_FULLSCREEN            2717
#define ID_CANCEL_EDIT_CNTR             2768
#define ID_GALLERY_STYLESET             2771
#define ID_PAGES_NEW                    2772
#define ID_PAGES_COVRE                  2773
#define ID_GALLERY_FONTFACE             2773
#define ID_PAGES_BREAK                  2774
#define ID_TABLE_NEW                    2775
#define ID_ILLUSTRATION_PICTURE         2776
#define ID_ILLUSTRATION_GRAPHIC         2777
#define ID_ILLUSTRATION_CHART           2778
#define ID_TABLE_INSERTTABLE            2779
#define ID_FILE_PRINT_LABEL             2779
#define ID_INSERT_HEADER                2780
#define ID_INSERT_FOOTER                2781
#define ID_INSERT_PAGENUMBER            2782
#define ID_TEXT_TEXTBOX                 2783
#define ID_TEXT_PARTS                   2784
#define ID_TEXT_WORDART                 2785
#define ID_TEXT_DROPCAP                 2786
#define ID_SYMBOL_EQUATIONS             2787
#define ID_SYMBOL_SYMBOL                2788
#define ID_PAGES_COVER                  2789
#define ID_ILLUSTRATION_CLIPART         2790
#define ID_GROUP_CLIPBOARD_OPTION       2790
#define ID_ILLUSTRATION_FROMCAMERA      2791
#define ID_INSERT_BOOKMARK              2791
#define ID_PAGENUMBER_FORMATPAGENUMBERS 2792
#define ID_FONT_GROW                    2792
#define ID_PAGENUMBER_REMOVEPAGENUMBERS 2793
#define ID_FONT_SHRINK                  2793
#define ID_NEWPAGE_BLANKPAGE            2794
#define ID_FONT_CLEAR                   2794
#define ID_NEWPAGE_SELECTION            2795
#define ID_TEXT_CHANGECASE              2795
#define ID_INSERT_NUMBERING             2796
#define ID_INSERT_LIST                  2797
#define ID_PARA_DECREASEINDENT          2798
#define ID_PARA_INCREASEINDENT          2799
#define ID_PARA_SORT                    2800
#define ID_PARA_JUSTIFY                 2801
#define ID_PARA_SHOWMARKS               2802
#define ID_DOCUMENTPARTS_AUTOTEXT       2803
#define ID_PARA_LINESPACING             2803
#define ID_DOCUMENTPARTS_PROPERTY       2804
#define ID_PARA_SHADING                 2804
#define ID_DOCUMENTPARTS_FIELD          2805
#define ID_BORDERS_NOBORDER             2805
#define ID_DOCUMENTPARTS_BUILDINGBLOCKORGANIZER 2806
#define ID_TEXT_HIGHLIGHTCOLOR          2806
#define ID_VIEW_RULER                   2807
#define ID_VIEW_GRIDLINES               2808
#define ID_VIEW_PROPERTIES              2809
#define ID_VIEW_DOCUMENTMAP             2810
#define ID_VIEW_THUMBNAILS              2811
#define ID_VIEW_ACTINBAR                2812
#define ID_TEXT_COLOR_SELECTOR          2813
#define ID_THEMES_OFFICE                2814
#define ID_STYLES_CHANGE                2815
#define ID_PARAGRAPH_INDENT             2816
#define ID_PARAGRAPH_INDENTLEFT         2817
#define ID_PARAGRAPH_INDENTRIGHT        2818
#define ID_PARAGRAPH_SPACING            2819
#define ID_PARAGRAPH_SPACINGBEFORE      2820
#define ID_PARAGRAPH_SPACINGAFTER       2821
#define ID_FILE_SEND_LABEL              2822
#define ID_GALLERY_COLUMNS              2900
#define ID_GALLERY_SHAPES               3000
#define ID_GALLERY_STYLES               3001
#define ID_THEMES_BUILTIN               3813
#define ID_TAB_WRITE                    5004
#define ID_TAB_HOME                     5004
#define ID_TAB_INSERT                   5005
#define ID_TAB_PAGELAYOUT               5006
#define ID_TAB_ADDINS                   5007
#define ID_TAB_TABLEDESIGN              5008
#define ID_TAB_TABLELAYOUT              5009
#define ID_TAB_CHARTDESIGN              5010
#define ID_TAB_CHARTFORMAT              5011
#define ID_TAB_CHARTLAYOUT              5012
#define ID_TAB_CONTEXTCHART             5013
#define ID_TAB_SUBEDITOR                5014
#define ID_TAB_VIEW                     5026
#define ID_TAB_REFERENCES               5027
#define ID_TAB_MAILINGS                 5028
#define ID_TAB_REVIEW                   5029
#define ID_TAB_PICTUREFORMAT            5030
#define ID_MENU_FILE                    5032
#define ID_OPTIONS_STYLEBLUE            5840
#define ID_OPTIONS_STYLEBLACK           5841
#define ID_OPTIONS_STYLESILVER          5842
#define ID_OPTIONS_STYLEAQUA            5843
#define ID_OPTIONS_STYLESCENIC          5844
#define ID_OPTIONS_STYLEWHITE           5845
#define ID_OPTIONS_STYLESYSTEM          5846
#define ID_GROUP_TABLEOFCONTENTS        6000
#define ID_GROUP_FOOTNOTES              6001
#define ID_GROUP_INDEX                  6002
#define ID_GROUP_DOCUMENTVIEWS          6003
#define ID_GROUP_ZOOM                   6004
#define ID_GROUP_CAPTIONS               6005
#define ID_GROUP_WINDOW                 6006
#define ID_GROUP_PAGES                  6007
#define IDR_TOOLBAR_TODEDITOR           6007
#define ID_GROUP_TABLE                  6008
#define IDR_TOOLBAR_HIERARCHY           6008
#define ID_GROUP_ILLUSTRATIONS          6009
#define ID_GROUP_HEADERFOOTERS          6010
#define ID_GROUP_LINKS                  6011
#define ID_GROUP_TEXT                   6012
#define ID_GROUP_SYMBOLS                6013
#define ID_GROUP_THEMES                 6014
#define ID_GROUP_PAGESETUP              6015
#define ID_GROUP_PAGEBACKGROUND         6016
#define ID_GROUP_OBJSEL                 6016
#define ID_GROUP_ARRANGE                6017
#define ID_GROUP_EDITORS                6017
#define ID_GROUP_SHOWHIDE               6018
#define ID_GROUP_BASICPANE              6018
#define ID_GROUP_PARAGRAPH              6019
#define ID_GROUP_CLIPBOARD              6020
#define ID_GROUP_FONT                   6021
#define ID_GROUP_FIND                   6022
#define ID_GROUP_STYLES                 6023
#define ID_GROUP_SHAPES                 6024
#define ID_GROUP_FONT_OPTION            6025
#define ID_GROUP_STYLES_OPTION          6026
#define ID_GROUP_PARAGRAPH_OPTION       6027
#define ID_GROUP_FIND_OPTION            6028
#define ID_GROUP_PAGEPARAGRAPH          6028
#define ID_GROUP_GKOBJMOVEMENT          6029
#define ID_GROUP_OBJ                    6029
#define ID_CHAR_BOLD                    7608
#define ID_CHAR_ITALIC                  7610
#define ID_CHAR_UNDERLINE               7611
#define ID_EDIT_GOTO                    7612
#define ID_EDIT_SELECT_OBJECTS          7613
#define ID_EDIT_SELECT                  7614
#define ID_EDIT_SELECT_MULTIPLE_OBJECTS 7615
#define ID_FORMAT_PAINTER               7616
#define ID_TEXT_FONT                    7617
#define ID_FONT_FACE                    7618
#define ID_FONT_SIZE                    7619
#define ID_CHAR_STRIKETHROUGH           7620
#define ID_TEXT_SUBSCRIPT               7621
#define ID_TEXT_SUPERSCRIPT             7622
#define ID_TEXT_COLOR                   7623
#define ID_SWITCH_PRINTLAYOUT           7700
#define IDB_STATUSBAR_VIEWSWITCH        7700
#define ID_SWITCH_FULLSCREENREADING     7701
#define ID_SWITCH_WEBLAYOUT             7702
#define ID_SWITCH_OUTLINE               7703
#define ID_SWITCH_DRAFT                 7704
#define IDB_SYSTEMMENULARGE             8000
#define IDC_MESSAGEBAR_WARNING          22988
#define ID_CHANGESTYLES_STYLESET_RESET  32772
#define ID_CHANGESTYLES_FONTS_CREATENEWFONT 32775
#define ID_CHANGESTYLES_COLORS_CREATENEWTHEMECOLORS 32776
#define ID_INSERT_BULLET                32777
#define ID_QUICKSTYLES_APPLYSTYLE       32778
#define ID_FORMAT_FONTCOLOR_AUTOMATIC   32791
#define ID_FORMAT_FONTCOLOR_MORECOLORS  32792
#define ID_COVERPAGE_REMOVECURRENTCOVERPAGE 32796
#define ID_COVERPAGE_SAVESELECTIONASNEWCOVERPAGE 32797
#define ID_TABLE_DRAWTABLE              32799
#define ID_TABLE_CONVERTTEXTTOTABLE     32800
#define ID_TEXTBOX_DRAWTEXTBOX          32801
#define ID_TEXTBOX_SAVESELECTIONASNEWTEXTBOX 32802
#define ID_PARA_LEFT                    32803
#define ID_PARA_CENTER                  32804
#define ID_PARA_RIGHT                   32805
#define ID_EQUATIONS_MATH               32807
#define ID_FORMAT_FONTCOLOR_NOHIGHLIGHT 32807
#define ID_THEMES_COLORS                32808
#define ID_THEMES_FONTS                 32809
#define ID_THEMES_EFFECTS               32810
#define ID_PAGE_MOVEMODE_ORIENTATIONS   32811
#define ID_PAGE_MOVEMODE_ORIENTATION    32812
#define ID_PAGE_MOVEMODE_SCALE          32813
#define ID_PAGE_COLUMNS                 32814
#define ID_PAGE_BREAKS                  32815
#define ID_PAGE_LINENUMBERS             32816
#define ID_PAGE_HYPHENATATION           32817
#define ID_PAGE_TIMEOFDAY               32818
#define ID_PAGE_MATERIALEDITOR          32819
#define ID_PAGE_BORDERS                 32820
#define ID_ARRANGE_FRONT                32821
#define ID_ARRANGE_BACK                 32822
#define ID_ARRANGE_ALIGN                32823
#define ID_ARRANGE_GROUP                32824
#define ID_ARRANGE_UNGROUP              32825
#define ID_ARRANGE_ROTATE               32826
#define ID_THEMES_THEMES                32827
#define ID_PAGE_MOVEMODE_MOVE           32828
#define ID_ARRANGE_POSITION             32829
#define ID_ARRANGE_TEXTWRAPPING         32831
#define ID_CONTEXT_FONT                 32832
#define ID_PARA_PARAGRAPH               32833
#define ID_THEME_OFFICE2003             32834
#define ID_THEME_OFFICE2007             32835
#define ID_SHAPES_NEWDRAWING            32836
#define ID_OPTIONS_ANIMATION            32838
#define ID_OPTIONS_RIGHTTOLEFT          32839
#define ID_BACKCOLOR_NOCOLORS           32844
#define ID_TOGGLE_GROUPS                32845
#define ID_CONTENTS_TABLE               32846
#define ID_CONTENTS_ADDTEXT             32847
#define ID_CONTENTS_UPDATE              32848
#define ID_FOOTNOTES_INSERT             32849
#define ID_FOOTNOTES_INSEREND           32850
#define ID_FOOTNOTES_NEXT               32851
#define ID_FOOTNOTES_SHOW               32852
#define ID_INDEX_MARK                   32853
#define ID_INDEX_INSERT                 32854
#define ID_INDEX_UPDATE                 32855
#define ID_CAPTIONS_INSERT              32856
#define ID_CAPTIONS_FIGURES             32857
#define ID_CAPTIONS_UPDATE              32858
#define IOD_CAPTIONS_CROSSREFERENCE     32860
#define ID_VIEW_PRINTLAYOUT             32861
#define ID_VIEW_WEBLAYOUT               32863
#define ID_VIEW_OUTLINE                 32864
#define ID_VIEW_DRAFT                   32865
#define ID_ZOOM_ZOOM                    32866
#define ID_ZOOM_ONEPAGE                 32867
#define ID_ZOOM_TWOPAGES                32868
#define ID_ZOOM_PAGEWIDTH               32869
#define ID_WINDOW_SIDEBYSIDE            32870
#define ID_WINDOW_SYNCHRONOUSSCROLLING  32871
#define ID_WINDOW_RESET                 32872
#define ID_WINDOW_SWITCH                32873
#define ID_VIEW_FULLSCREENREADING       32874
#define ID_FILE_RECENTDOCUMENTS         32876
#define ID_FILE_SEND_INTERNETFAX        32878
#define ID_APP_CLOSE                    32879
#define ID_APP_OPTIONS                  32880
#define ID_FILE_SEND                    32881
#define ID_OPTIONS_FONT_SYSTEM          32883
#define ID_OPTIONS_FONT_NORMAL          32884
#define ID_OPTIONS_FONT_LARGE           32885
#define ID_OPTIONS_FONT_EXTRALARGE      32886
#define ID_OPTIONS_FONT_AUTORESIZEICONS 32887
#define ID_OPTIONS_FRAMETHEME           32888
#define ID_GK_MODEMOVE                  32889
#define ID_OBJ_06                       32890
#define ID_OBJ_SEL                      32891
#define ID_OBJ_MOVE                     32892
#define ID_OBJ_ROT                      32893
#define ID_OBJ_SCALE                    32894
#define ID_OBJ_05                       32895
#define ID_OBJ_07                       32896
#define ID_OBJ_08                       32897
#define ID_OBJ_09                       32898
#define ID_OBJ_10                       32899
#define ID_BUTTON_MATEDIT_GET           32902
#define ID_BUTTON_MATDEL                32903
#define ID_BUTTON_MATEDIT_SET           32904
#define ID_BUTTON_MATEDT_REFRESH        32905
#define ID_BUTTON_MATEDT_PICK           32907
#define ID_BUTTON32908                  32908
#define ID_BUTTON_MATEDT_CATE           32908
#define ID_BUTTON_TODEDT_PLAY           32909
#define ID_BUTTON_TODEDT_STOP           32910
#define ID_BUTTON_TODEDT_PREVKEY        32911
#define ID_BUTTON_TODEDT_NEXTKEY        32912
#define ID_BUTTON_TODEDT_PLANTKEY       32913
#define ID_BUTTON_TODEDT_DELKEY         32914
#define ID_BUTTON_TODEDT_FORWARD        32915
#define ID_BUTTON_TODEDT_CPYKEY         32916
#define ID_BUTTON_TODEDT_PSTKEY         32917
#define ID_FILE_PREPARE32918            32918
#define ID_FILE_PUBLISH                 32919
#define ID_SUBEDITOR_TIMEOFDAY          32920
#define ID_SUBEDITOR_MATERIALEDITOR     32921
#define ID_SUBEDITOR_HIERARCHY          32922
#define ID_SUBEDITOR_TERRIANEDITOR      32923
#define ID_SUBEDITOR_TRACKBUS           32924
#define ID_BUTTON_4                     32925
#define ID_BUTTON_5                     32926
#define ID_BUTTON_6                     32927
#define ID_SWITCH_CAM1                  32928
#define ID_SWITCH_CAM2                  32929
#define ID_SWITCH_CAM4                  32931
#define ID_SWITCH_CAM3                  32932
#define ID_SWITCH_CAM5                  32933
#define ID_SWITCH_CAM6                  32934
#define ID_SWITCH_CAM7                  32935
#define ID_SWITCH_CAM8                  32936
#define ID_SWITCH_CAM9                  32937
#define ID_SAVE_CAM1                    32938
#define ID_SAVE_CAM2                    32940
#define ID_SAVE_CAM3                    32941
#define ID_SAVE_CAM4                    32942
#define ID_SAVE_CAM5                    32943
#define ID_SAVE_CAM6                    32944
#define ID_SAVE_CAM7                    32945
#define ID_SAVE_CAM8                    32946
#define ID_SAVE_CAM9                    32947
#define ID_GLOBAL_FOCUSOBJ              32949
#define ID_OPTIONS_GKWHITE              32951
#define ID_OPTIONS_GKBLACK              32952
#define ID_BUTTON_1                     32953
#define ID_HRC_REFRESH                  32953
#define ID_BUTTON_2                     32954
#define ID_PANES_ID                     32954
#define ID_HRC_DELETE                   32954
#define ID_PANES_SWISSKNIFEBAR          32955
#define ID_PANES_MATERIALEDITOR         32956
#define ID_PANES_TRACKBUSEDITOR         32957
#define ID_PANES_CVAR                   32958
#define ID_PANES_TIMEOFDAYEDITOR        32959
#define ID_PANES_HIERARCHYEDITOR        32960
#define ID_PANES_TERRIANEDITOR          32961
#define ID_PANES_CHARACTEREDITOR        32962
#define ID_OPTIONS_ENGLISH              32963
#define ID_PANES_CONSOLE                32963
#define ID_OPTIONS_CHINESE              32964
#define ID_BUTTON_3                     32985
#define ID_HRC_FOCUS                    32985
#define ID_VIEW_MESSAGE_BAR             0xE806
#define ID_FILE_PREPARE                 65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        225
#define _APS_NEXT_COMMAND_VALUE         32967
#define _APS_NEXT_CONTROL_VALUE         1030
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
