export BUILT_PRODUCTS_DIR="/Users/gameknife/github/gkEngine/exec/ios/Release-OSX"
export CURRENT_ARCH="x86_64"
export OBJECT_FILE_DIR_normal="/Users/gameknife/github/gkEngine/intermediate/Release-OSX/gkLauncherMac.build/Objects-normal"
export OBJROOT="/Users/gameknife/github/gkEngine/intermediate/Release-OSX"
export PRECOMPS_INCLUDE_HEADERS_FROM_BUILT_PRODUCTS_DIR="YES"
export SRCROOT="/Users/gameknife/github/gkEngine/code/engine"
